[package]
name = "my-reverse-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-extensions = { tag = "0.1.4", git = "https://github.com/MyJetTools/rust-extensions.git" }

my-settings-reader = { tag = "0.3.0", git = "https://github.com/MyJetTools/my-settings-reader.git", features = [
    "background-reader",
] }

hyper = { version = "*", features = ["full"] }

tokio = { version = "*", features = ["full"] }
hyper-util = { version = "*", features = ["tokio"] }
http-body-util = "*"
tokio-rustls = { version = "0.24.1" }
bytes = "*"
lazy_static = "*"
pem = "*"
serde = { version = "*", features = ["derive"] }

serde_yaml = "*"
