name: Release App
on:
  push:
    tags: "*"

env:
  IMAGE_NAME: ghcr.io/myjettools/my-reverse-proxy

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: stable

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})
        
      - name: Updating version
        run: sed -i -e 's/^version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml


      - name: Build
        run: |
          export GIT_HUB_TOKEN="${{ secrets.PUBLISH_TOKEN }}"
          cargo build --release


      - name: Docker login
        run: |          
          echo "${{ secrets.PUBLISH_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin   
      - name: Docker Build and Publish
        run: |          
          docker build -t ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }} .
          docker push ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}

